### ISSUE TITLE
Incompatible with Optifine 1.16

### ISSUE THREAD

**Issue by poots6** [ErdbeerbaerLP/ErdbeerbaerGuiLib#6]
Game crashes with the error below. I've tested with all my other mods, and only Optifine and eguilib get this crash.

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 9/28/20 9:38 PM
Description: Rendering overlay

java.lang.NoClassDefFoundError: Could not initialize class javax.imageio.ImageIO
	at net.optifine.util.TextureUtils.getImageSize(TextureUtils.java:669) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.texture.AtlasTexture.detectMinimumSpriteSize(AtlasTexture.java:817) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.texture.AtlasTexture.detectMaxMipmapLevel(AtlasTexture.java:780) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.texture.AtlasTexture.func_229220_a_(AtlasTexture.java:276) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.model.ModelBakery.processLoading(ModelBakery.java:257) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraftforge.client.model.ModelLoader.<init>(ModelLoader.java:72) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.model.ModelManager.func_212854_a_(ModelManager.java:57) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.model.ModelManager.func_212854_a_(ModelManager.java:20) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.ReloadListener.func_215270_b(SourceFile:11) ~[?:?] {re:classloading}
	at net.minecraft.client.resources.ReloadListener$$Lambda$3338/721286839.get(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1574) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.optifine.util.TextureUtils.getImageSize(TextureUtils.java:669) ~[?:?] {re:classloading}
-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.ResourceLoadProgressGui
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:807) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:584) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.0.jar:34.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$443/1420623741.call(Unknown Source) [forge-1.16.3-34.1.0.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6780655072 bytes (6466 MB) / 7247757312 bytes (6912 MB) up to 10737418240 bytes (10240 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 7.0.1+78+master.e9771d8
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.1.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.3-34.1.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.3-34.1.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.0.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.1.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.3_HD_U_G3.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.3-34.1.0.jar fml TRANSFORMATIONSERVICE 
	FML: 34.1
	Forge: net.minecraftforge:34.1.0
	FML Language Providers: 
		javafml@34.1
		minecraft@1
	Mod List: 
		forge-1.16.3-34.1.0-client.jar Minecraft {minecraft@1.16.3 NONE}
		randomblockplacement-1.16.2-forge33.0.5-1.0.jar RandomBlockPlacement {randomblockplacement@1.16.2-forge33.0.5-1.0 NONE}
		eguilib-1.0.3-1.16.jar Erdbeerbaer's GUI Library {eguilib@1.0.3 NONE}
		forge-1.16.3-34.1.0-universal.jar Forge {forge@34.1.0 NONE}
		worldedit-forge-mc1.16.3-7.2.0-beta-05.jar WorldEdit {worldedit@7.2.0-beta-05+20b3da4 NONE}
		MinersAdvantage-1.16.3-1.7.3.153-1.16.jar MinersAdvantage {minersadvantage@1.16.3-1.7.3.153 NONE}
	Launched Version: 1.16.3-forge-34.1.0
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 452.06, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fabulous
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
	OptiFine Version: OptiFine_1.16.3_HD_U_G3
	OptiFine Build: 20200916-082411
	Render Distance Chunks: 20
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 452.06
	OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by ErdbeerbaerLP** [comment]
(Forgot to close)
Should be fixed now
